# Generated by Django 4.2.25 on 2025-10-22 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_description',
            field=models.TextField(blank=True, help_text=' Enter a short description of the recipe ', max_length=300),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(default='no_picture.jpg', help_text='Upload Image here', upload_to='recipes'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(help_text='Enter the cooking time in minutes', validators=[django.core.validators.MinValueValidator(1, message='Cooking time must be at least 1 minute'), django.core.validators.MaxValueValidator(1440, message='Cooking time cannot exceed 24 hours (1440 minutes)')]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(blank=True, help_text='Difficulty level calculated automatically', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(help_text='Enter the ingredients (comma separated)', max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(help_text='Enter recipe name ', max_length=120),
        ),
    ]
